Tenders/Models/OrgTender.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Tenders.Models;
using System.ComponentModel.DataAnnotations;

namespace Tenders.Models
{
    public class OrgTender
    {
        [Key]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        
        public int OrgTenderID { get; set; }

        [Display(Name = "Справочник организаторов тендеров")]
        public string ListOrgTender { get; set; }
    }
}

Tenders/Controllers/OrgTendersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tenders.Models;

namespace Tenders.Controllers
{
    public class OrgTendersController : Controller
    {
        private TenderContext db = new TenderContext();

   
        public async Task<ActionResult> Index()
        {
            return View(await db.orgTenders.ToListAsync());
        }

        
   
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "OrgTenderID,ListOrgTender")] OrgTender orgTender)
        {
            if (ModelState.IsValid)
            {
                db.orgTenders.Add(orgTender);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(orgTender);
        }

 
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrgTender orgTender = await db.orgTenders.FindAsync(id);
            if (orgTender == null)
            {
                return HttpNotFound();
            }
            return View(orgTender);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "OrgTenderID,ListOrgTender")] OrgTender orgTender)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orgTender).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(orgTender);
        }


        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrgTender orgTender = await db.orgTenders.FindAsync(id);
            if (orgTender == null)
            {
                return HttpNotFound();
            }
            return View(orgTender);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            OrgTender orgTender = await db.orgTenders.FindAsync(id);
            db.orgTenders.Remove(orgTender);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tenders/Views/OrgTenders/Create.cshtml
@model Tenders.Models.OrgTender





@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ListOrgTender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ListOrgTender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ListOrgTender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
                <a class="btn btn-default" href=" @Url.Action("Index", "OrgTenders")">Назад</a>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tenders/Views/OrgTenders/Delete.cshtml
@model Tenders.Models.OrgTender




<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ListOrgTender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ListOrgTender)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            <a class="btn btn-default" href=" @Url.Action("Index", "OrgTenders")">Назад</a>
        </div>
    }
</div>

Tenders/Views/OrgTenders/Edit.cshtml
@model Tenders.Models.OrgTender





@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
    
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrgTenderID)

        <div class="form-group">
            @Html.LabelFor(model => model.ListOrgTender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ListOrgTender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ListOrgTender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
                <a class="btn btn-default" href=" @Url.Action("Index", "OrgTenders")">Назад</a>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tenders/Views/OrgTenders/Index.cshtml
@model IEnumerable<Tenders.Models.OrgTender>



</br>
<div class="form-group">

    <a class="btn btn-default"  href=" @Url.Action("Create", "OrgTenders")">Создать нового организатора</a>
  
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ListOrgTender)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ListOrgTender)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id=item.OrgTenderID }) |       
            @Html.ActionLink("Удалить", "Delete", new { id=item.OrgTenderID })
        </td>
    </tr>
}

</table>