Tenders/Models/ViewTender.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Tenders.Models;
using System.ComponentModel.DataAnnotations;

namespace Tenders.Models
{
    public class ViewTender
    {
        [Key]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        
        public int ViewTenderID { get; set; }
        [Display(Name = "Справочник видов")]
        public string ListViewTenders { get; set; }

    }
}

Tenders/Controllers/ViewTendersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tenders.Models;

namespace Tenders.Controllers
{
    public class ViewTendersController : Controller
    {
        private TenderContext db = new TenderContext();

        
        public async Task<ActionResult> Index()
        {
            return View(await db.viewTenders.ToListAsync());
        }

       
       
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ViewTenderID,ListViewTenders")] ViewTender viewTender)
        {
            if (ModelState.IsValid)
            {
                db.viewTenders.Add(viewTender);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(viewTender);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewTender viewTender = await db.viewTenders.FindAsync(id);
            if (viewTender == null)
            {
                return HttpNotFound();
            }
            return View(viewTender);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ViewTenderID,ListViewTenders")] ViewTender viewTender)
        {
            if (ModelState.IsValid)
            {
                db.Entry(viewTender).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(viewTender);
        }

    
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewTender viewTender = await db.viewTenders.FindAsync(id);
            if (viewTender == null)
            {
                return HttpNotFound();
            }
            return View(viewTender);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ViewTender viewTender = await db.viewTenders.FindAsync(id);
            db.viewTenders.Remove(viewTender);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tenders/Views/ViewTenders/Create.cshtml
@model Tenders.Models.ViewTender





</br>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ListViewTenders, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ListViewTenders, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ListViewTenders, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
                <a class="btn btn-default" href=" @Url.Action("Index", "ViewTenders")">Назад</a>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tenders/Views/ViewTenders/Delete.cshtml
@model Tenders.Models.ViewTender




</br>
<div>

   
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ListViewTenders)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ListViewTenders)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" />
            <a class="btn btn-default" href=" @Url.Action("Index", "ViewTenders")">Назад</a>

        </div>
    }
</div>

Tenders/Views/ViewTenders/Edit.cshtml
@model Tenders.Models.ViewTender




</br>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
     
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ViewTenderID)

        <div class="form-group">
            @Html.LabelFor(model => model.ListViewTenders, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ListViewTenders, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ListViewTenders, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
                <a class="btn btn-default" href=" @Url.Action("Index", "ViewTenders")">Назад</a>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tenders/Views/ViewTenders/Index.cshtml
@model IEnumerable<Tenders.Models.ViewTender>



</br>
<div class="form-group">

    <a class="btn btn-default" href=" @Url.Action("Create", "ViewTenders")">Создать новый вид</a>

</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ListViewTenders)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ListViewTenders)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id=item.ViewTenderID }) |    
            @Html.ActionLink("Удалить", "Delete", new { id=item.ViewTenderID })
        </td>
    </tr>
}

</table>