Tenders/Models/CurrencyBudget.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Tenders.Models;
using System.ComponentModel.DataAnnotations;

namespace Tenders.Models
{
    public class CurrencyBudget
    {
        [Key]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public int CurrencyBudgetID { get; set; }
        [Display(Name = "Справочник валют")]
        public string ListCurrencyBudget { get; set; }
    }
}

Tenders/Controllers/CurrencyBudgetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tenders.Models;

namespace Tenders.Controllers
{
    public class CurrencyBudgetsController : Controller
    {
        private TenderContext db = new TenderContext();

     
        public async Task<ActionResult> Index()
        {
            return View(await db.currencyBudgets.ToListAsync());
        }

      
    
     
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CurrencyBudgetID,ListCurrencyBudget")] CurrencyBudget currencyBudget)
        {
            if (ModelState.IsValid)
            {
                db.currencyBudgets.Add(currencyBudget);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(currencyBudget);
        }

 
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CurrencyBudget currencyBudget = await db.currencyBudgets.FindAsync(id);
            if (currencyBudget == null)
            {
                return HttpNotFound();
            }
            return View(currencyBudget);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CurrencyBudgetID,ListCurrencyBudget")] CurrencyBudget currencyBudget)
        {
            if (ModelState.IsValid)
            {
                db.Entry(currencyBudget).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(currencyBudget);
        }

   
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CurrencyBudget currencyBudget = await db.currencyBudgets.FindAsync(id);
            if (currencyBudget == null)
            {
                return HttpNotFound();
            }
            return View(currencyBudget);
        }

     
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CurrencyBudget currencyBudget = await db.currencyBudgets.FindAsync(id);
            db.currencyBudgets.Remove(currencyBudget);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tenders/Views/CurrencyBudgets/Create.cshtml
@model Tenders.Models.CurrencyBudget





@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
     
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ListCurrencyBudget, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ListCurrencyBudget, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ListCurrencyBudget, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cохранить" class="btn btn-default" />
                <a class="btn btn-default" href=" @Url.Action("Index", "CurrencyBudgets")">Назад</a>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tenders/Views/CurrencyBudgets/Delete.cshtml
@model Tenders.Models.CurrencyBudget




<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ListCurrencyBudget)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ListCurrencyBudget)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Удалить" class="btn btn-default" /> 
        <a class="btn btn-default" href=" @Url.Action("Index", "CurrencyBudgets")">Назад</a>
       
    </div>
    }
</div>

Tenders/Views/CurrencyBudgets/Edit.cshtml
@model Tenders.Models.CurrencyBudget





@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CurrencyBudgetID)

        <div class="form-group">
            @Html.LabelFor(model => model.ListCurrencyBudget, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ListCurrencyBudget, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ListCurrencyBudget, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
                <a class="btn btn-default" href=" @Url.Action("Index", "CurrencyBudgets")">Назад</a>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tenders/Views/CurrencyBudgets/Index.cshtml
@model IEnumerable<Tenders.Models.CurrencyBudget>




</br>
<div class="form-group">

    <a class="btn btn-default" href=" @Url.Action("Create", "CurrencyBudgets")">Создать новый бюджет</a>

</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ListCurrencyBudget)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ListCurrencyBudget)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.CurrencyBudgetID }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.CurrencyBudgetID })
            </td>
        </tr>
    }

</table>